window.AYO_FEEDBACK_UI = {
pl:{button:"Zgłoś uwagę",title:"Zgłoś uwagę",intro:"Znalazłeś błąd, masz pomysł albo pytanie? Opisz je tutaj.",note:"Zgłoszenie otworzy się jako nowe GitHub Issue. Adres e-mail autora strony nie jest publikowany.",program:"Program",type:"Rodzaj zgłoszenia",message:"Wiadomość",send:"Przejdź do wysłania",bug:"Błąd",suggestion:"Sugestia",question:"Pytanie",other:"Inne",required:"Wpisz wiadomość przed wysłaniem.",opening:"Otwieram zgłoszenie w GitHub…",pageLanguage:"Język strony",source:"Źródło"},
en:{button:"Send feedback",title:"Send feedback",intro:"Found a bug, have an idea, or want to ask a question? Describe it here.",note:"The report opens as a new GitHub Issue. The site owner's email address is not published.",program:"Application",type:"Feedback type",message:"Message",send:"Continue to submit",bug:"Bug",suggestion:"Suggestion",question:"Question",other:"Other",required:"Write a message before submitting.",opening:"Opening GitHub issue…",pageLanguage:"Page language",source:"Source"},
sq:{button:"Dërgo koment",title:"Dërgo koment",intro:"Gjete një gabim, ke një ide ose pyetje? Shkruaje këtu.",note:"Raporti do të hapet si një GitHub Issue i ri. Adresa e emailit të autorit nuk publikohet.",program:"Programi",type:"Lloji i raportit",message:"Mesazhi",send:"Vazhdo me dërgimin",bug:"Gabim",suggestion:"Sugjerim",question:"Pyetje",other:"Tjetër",required:"Shkruaj një mesazh para dërgimit.",opening:"Po hap GitHub Issue…",pageLanguage:"Gjuha e faqes",source:"Burimi"},
hy:{button:"Ուղարկել կարծիք",title:"Ուղարկել կարծիք",intro:"Գտե՞լ եք սխալ, ունե՞ք առաջարկ կամ հարց։ Գրեք այստեղ։",note:"Հաղորդագրությունը կբացվի որպես նոր GitHub Issue։ Կայքի հեղինակի էլ․ հասցեն չի հրապարակվում։",program:"Ծրագիր",type:"Հաղորդման տեսակ",message:"Հաղորդագրություն",send:"Շարունակել ուղարկել",bug:"Սխալ",suggestion:"Առաջարկ",question:"Հարց",other:"Այլ",required:"Ուղարկելուց առաջ գրեք հաղորդագրություն։",opening:"Բացվում է GitHub Issue…",pageLanguage:"Էջի լեզու",source:"Աղբյուր"},
az:{button:"Rəy göndər",title:"Rəy göndər",intro:"Səhv tapdınız, təklifiniz və ya sualınız var? Burada yazın.",note:"Müraciət yeni GitHub Issue kimi açılacaq. Sayt müəllifinin e-poçtu yayımlanmır.",program:"Proqram",type:"Müraciət növü",message:"Mesaj",send:"Göndərməyə davam et",bug:"Səhv",suggestion:"Təklif",question:"Sual",other:"Digər",required:"Göndərməzdən əvvəl mesaj yazın.",opening:"GitHub Issue açılır…",pageLanguage:"Səhifə dili",source:"Mənbə"},
eu:{button:"Bidali iritzia",title:"Bidali iritzia",intro:"Akats bat aurkitu duzu, ideia bat duzu edo galdera bat? Idatzi hemen.",note:"Txostena GitHub Issue berri gisa irekiko da. Webgunearen egilearen helbide elektronikoa ez da argitaratzen.",program:"Aplikazioa",type:"Txosten mota",message:"Mezua",send:"Jarraitu bidaltzera",bug:"Akatsa",suggestion:"Iradokizuna",question:"Galdera",other:"Bestelakoa",required:"Idatzi mezua bidali aurretik.",opening:"GitHub Issue irekitzen…",pageLanguage:"Orriaren hizkuntza",source:"Iturria"},
bs:{button:"Pošalji povratnu informaciju",title:"Pošalji povratnu informaciju",intro:"Pronašli ste grešku, imate ideju ili pitanje? Opišite ovdje.",note:"Prijava će se otvoriti kao novi GitHub Issue. E-mail autora stranice nije objavljen.",program:"Program",type:"Vrsta prijave",message:"Poruka",send:"Nastavi na slanje",bug:"Greška",suggestion:"Prijedlog",question:"Pitanje",other:"Ostalo",required:"Unesite poruku prije slanja.",opening:"Otvaram GitHub Issue…",pageLanguage:"Jezik stranice",source:"Izvor"},
bg:{button:"Изпрати отзив",title:"Изпрати отзив",intro:"Открихте грешка, имате идея или въпрос? Опишете го тук.",note:"Сигналът ще се отвори като нов GitHub Issue. Имейлът на автора на сайта не се публикува.",program:"Програма",type:"Тип сигнал",message:"Съобщение",send:"Продължи към изпращане",bug:"Грешка",suggestion:"Предложение",question:"Въпрос",other:"Друго",required:"Въведете съобщение преди изпращане.",opening:"Отварям GitHub Issue…",pageLanguage:"Език на страницата",source:"Източник"},
ca:{button:"Envia comentaris",title:"Envia comentaris",intro:"Has trobat un error, tens una idea o una pregunta? Explica-ho aquí.",note:"L'informe s'obrirà com una nova GitHub Issue. El correu de l'autor del lloc no es publica.",program:"Aplicació",type:"Tipus d'informe",message:"Missatge",send:"Continua per enviar",bug:"Error",suggestion:"Suggeriment",question:"Pregunta",other:"Altres",required:"Escriu un missatge abans d'enviar.",opening:"Obrint GitHub Issue…",pageLanguage:"Idioma de la pàgina",source:"Font"},
co:{button:"Mandà un parè",title:"Mandà un parè",intro:"Avete trovu un sbagliu, avete un'idea o una dumanda? Scrivitelu quì.",note:"U raportu s'aprirà cum'è un novu GitHub Issue. L'indirizzu email di l'autore ùn hè micca publicatu.",program:"Applicazione",type:"Tipu di raportu",message:"Missaghju",send:"Cuntinuà per mandà",bug:"Sbagliu",suggestion:"Suggerimentu",question:"Dumanda",other:"Altru",required:"Scrivite un missaghju prima di mandà.",opening:"Apertura di GitHub Issue…",pageLanguage:"Lingua di a pagina",source:"Fonte"},
hr:{button:"Pošalji povratnu informaciju",title:"Pošalji povratnu informaciju",intro:"Pronašli ste pogrešku, imate ideju ili pitanje? Opišite ovdje.",note:"Prijava će se otvoriti kao novi GitHub Issue. E-mail autora stranice nije objavljen.",program:"Program",type:"Vrsta prijave",message:"Poruka",send:"Nastavi na slanje",bug:"Pogreška",suggestion:"Prijedlog",question:"Pitanje",other:"Ostalo",required:"Unesite poruku prije slanja.",opening:"Otvaram GitHub Issue…",pageLanguage:"Jezik stranice",source:"Izvor"},
cs:{button:"Odeslat zpětnou vazbu",title:"Odeslat zpětnou vazbu",intro:"Našli jste chybu, máte nápad nebo otázku? Napište ji sem.",note:"Hlášení se otevře jako nový GitHub Issue. E-mail autora webu se nezveřejňuje.",program:"Aplikace",type:"Typ hlášení",message:"Zpráva",send:"Pokračovat k odeslání",bug:"Chyba",suggestion:"Návrh",question:"Otázka",other:"Jiné",required:"Před odesláním napište zprávu.",opening:"Otevírám GitHub Issue…",pageLanguage:"Jazyk stránky",source:"Zdroj"},
da:{button:"Send feedback",title:"Send feedback",intro:"Har du fundet en fejl, en idé eller et spørgsmål? Beskriv det her.",note:"Rapporten åbnes som et nyt GitHub Issue. Sideejerens e-mailadresse offentliggøres ikke.",program:"Program",type:"Type feedback",message:"Besked",send:"Fortsæt til indsendelse",bug:"Fejl",suggestion:"Forslag",question:"Spørgsmål",other:"Andet",required:"Skriv en besked før du sender.",opening:"Åbner GitHub Issue…",pageLanguage:"Sidens sprog",source:"Kilde"},
nl:{button:"Feedback sturen",title:"Feedback sturen",intro:"Een fout gevonden, een idee of een vraag? Beschrijf het hier.",note:"De melding wordt geopend als een nieuwe GitHub Issue. Het e-mailadres van de site-eigenaar wordt niet gepubliceerd.",program:"Programma",type:"Type melding",message:"Bericht",send:"Doorgaan naar verzenden",bug:"Fout",suggestion:"Suggestie",question:"Vraag",other:"Overig",required:"Schrijf een bericht voordat je verzendt.",opening:"GitHub Issue openen…",pageLanguage:"Paginataal",source:"Bron"},
et:{button:"Saada tagasiside",title:"Saada tagasiside",intro:"Leidsid vea, sul on idee või küsimus? Kirjelda seda siin.",note:"Teade avatakse uue GitHub Issue'na. Lehe autori e-posti aadressi ei avaldata.",program:"Rakendus",type:"Teate tüüp",message:"Sõnum",send:"Jätka saatmisega",bug:"Viga",suggestion:"Soovitus",question:"Küsimus",other:"Muu",required:"Kirjuta enne saatmist sõnum.",opening:"Avan GitHub Issue…",pageLanguage:"Lehe keel",source:"Allikas"},
fi:{button:"Lähetä palautetta",title:"Lähetä palautetta",intro:"Löysitkö virheen, onko sinulla idea tai kysymys? Kirjoita se tähän.",note:"Palaute avataan uutena GitHub Issuena. Sivuston tekijän sähköpostiosoitetta ei julkaista.",program:"Ohjelma",type:"Palautteen tyyppi",message:"Viesti",send:"Jatka lähetykseen",bug:"Virhe",suggestion:"Ehdotus",question:"Kysymys",other:"Muu",required:"Kirjoita viesti ennen lähettämistä.",opening:"Avataan GitHub Issue…",pageLanguage:"Sivun kieli",source:"Lähde"},
fr:{button:"Envoyer un avis",title:"Envoyer un avis",intro:"Vous avez trouvé un bug, une idée ou une question ? Décrivez-la ici.",note:"Le signalement s'ouvrira comme une nouvelle GitHub Issue. L'adresse e-mail de l'auteur du site n'est pas publiée.",program:"Application",type:"Type de signalement",message:"Message",send:"Continuer vers l'envoi",bug:"Bug",suggestion:"Suggestion",question:"Question",other:"Autre",required:"Écrivez un message avant l'envoi.",opening:"Ouverture de GitHub Issue…",pageLanguage:"Langue de la page",source:"Source"},
gl:{button:"Enviar comentarios",title:"Enviar comentarios",intro:"Atopaches un erro, tes unha idea ou unha pregunta? Escríbea aquí.",note:"O informe abrirase como unha nova GitHub Issue. O correo do autor da web non se publica.",program:"Aplicación",type:"Tipo de informe",message:"Mensaxe",send:"Continuar para enviar",bug:"Erro",suggestion:"Suxestión",question:"Pregunta",other:"Outro",required:"Escribe unha mensaxe antes de enviar.",opening:"Abrindo GitHub Issue…",pageLanguage:"Idioma da páxina",source:"Fonte"},
ka:{button:"გამოხმაურების გაგზავნა",title:"გამოხმაურების გაგზავნა",intro:"იპოვეთ შეცდომა, გაქვთ იდეა ან კითხვა? აღწერეთ აქ.",note:"შეტყობინება გაიხსნება როგორც ახალი GitHub Issue. საიტის ავტორის ელფოსტა არ ქვეყნდება.",program:"პროგრამა",type:"შეტყობინების ტიპი",message:"შეტყობინება",send:"გაგზავნაზე გადასვლა",bug:"შეცდომა",suggestion:"წინადადება",question:"კითხვა",other:"სხვა",required:"გაგზავნამდე დაწერეთ შეტყობინება.",opening:"GitHub Issue იხსნება…",pageLanguage:"გვერდის ენა",source:"წყარო"},
de:{button:"Feedback senden",title:"Feedback senden",intro:"Fehler gefunden, eine Idee oder Frage? Beschreibe sie hier.",note:"Die Meldung wird als neues GitHub Issue geöffnet. Die E-Mail-Adresse des Seitenautors wird nicht veröffentlicht.",program:"Anwendung",type:"Art der Meldung",message:"Nachricht",send:"Weiter zum Senden",bug:"Fehler",suggestion:"Vorschlag",question:"Frage",other:"Sonstiges",required:"Bitte vor dem Senden eine Nachricht eingeben.",opening:"GitHub Issue wird geöffnet…",pageLanguage:"Seitensprache",source:"Quelle"},
el:{button:"Αποστολή σχολίου",title:"Αποστολή σχολίου",intro:"Βρήκατε σφάλμα, έχετε ιδέα ή ερώτηση; Περιγράψτε το εδώ.",note:"Η αναφορά θα ανοίξει ως νέο GitHub Issue. Το email του δημιουργού της σελίδας δεν δημοσιεύεται.",program:"Εφαρμογή",type:"Τύπος αναφοράς",message:"Μήνυμα",send:"Συνέχεια για αποστολή",bug:"Σφάλμα",suggestion:"Πρόταση",question:"Ερώτηση",other:"Άλλο",required:"Γράψτε μήνυμα πριν την αποστολή.",opening:"Άνοιγμα GitHub Issue…",pageLanguage:"Γλώσσα σελίδας",source:"Πηγή"},
hu:{button:"Visszajelzés küldése",title:"Visszajelzés küldése",intro:"Hibát találtál, van ötleted vagy kérdésed? Írd le itt.",note:"A bejelentés új GitHub Issue-ként nyílik meg. Az oldal készítőjének e-mail-címe nem kerül közzétételre.",program:"Alkalmazás",type:"Visszajelzés típusa",message:"Üzenet",send:"Tovább a küldéshez",bug:"Hiba",suggestion:"Javaslat",question:"Kérdés",other:"Egyéb",required:"Küldés előtt írj üzenetet.",opening:"GitHub Issue megnyitása…",pageLanguage:"Oldal nyelve",source:"Forrás"},
is:{button:"Senda ábendingu",title:"Senda ábendingu",intro:"Fannstu villu, hefurðu hugmynd eða spurningu? Lýstu því hér.",note:"Tilkynningin opnast sem nýtt GitHub Issue. Netfang höfundar síðunnar er ekki birt.",program:"Forrit",type:"Tegund ábendingar",message:"Skilaboð",send:"Halda áfram í sendingu",bug:"Villa",suggestion:"Tillaga",question:"Spurning",other:"Annað",required:"Skrifaðu skilaboð áður en þú sendir.",opening:"Opna GitHub Issue…",pageLanguage:"Tungumál síðu",source:"Heimild"},
ga:{button:"Seol aiseolas",title:"Seol aiseolas",intro:"Ar aimsigh tú fabht, an bhfuil smaoineamh nó ceist agat? Déan cur síos anseo.",note:"Osclófar an tuairisc mar GitHub Issue nua. Ní fhoilsítear seoladh ríomhphoist údar an tsuímh.",program:"Feidhmchlár",type:"Cineál aiseolais",message:"Teachtaireacht",send:"Lean ar aghaidh le seoladh",bug:"Fabht",suggestion:"Moladh",question:"Ceist",other:"Eile",required:"Scríobh teachtaireacht sula seolann tú.",opening:"GitHub Issue á oscailt…",pageLanguage:"Teanga an leathanaigh",source:"Foinse"},
it:{button:"Invia feedback",title:"Invia feedback",intro:"Hai trovato un errore, hai un'idea o una domanda? Descrivila qui.",note:"La segnalazione si aprirà come una nuova GitHub Issue. L'indirizzo e-mail dell'autore del sito non viene pubblicato.",program:"Applicazione",type:"Tipo di segnalazione",message:"Messaggio",send:"Continua per inviare",bug:"Errore",suggestion:"Suggerimento",question:"Domanda",other:"Altro",required:"Scrivi un messaggio prima di inviare.",opening:"Apertura GitHub Issue…",pageLanguage:"Lingua della pagina",source:"Fonte"},
ja:{button:"フィードバックを送る",title:"フィードバックを送る",intro:"不具合、提案、質問がありますか？ここに入力してください。",note:"内容は新しい GitHub Issue として開きます。サイト作者のメールアドレスは公開されません。",program:"アプリ",type:"種類",message:"メッセージ",send:"送信へ進む",bug:"不具合",suggestion:"提案",question:"質問",other:"その他",required:"送信前にメッセージを入力してください。",opening:"GitHub Issue を開いています…",pageLanguage:"ページの言語",source:"参照元"},
kk:{button:"Пікір жіберу",title:"Пікір жіберу",intro:"Қате таптыңыз ба, ұсыныс немесе сұрақ бар ма? Осында жазыңыз.",note:"Хабарлама жаңа GitHub Issue ретінде ашылады. Сайт авторының электрондық поштасы жарияланбайды.",program:"Бағдарлама",type:"Хабарлама түрі",message:"Хабарлама",send:"Жіберуге өту",bug:"Қате",suggestion:"Ұсыныс",question:"Сұрақ",other:"Басқа",required:"Жібермес бұрын хабарлама жазыңыз.",opening:"GitHub Issue ашылуда…",pageLanguage:"Бет тілі",source:"Дереккөз"},
lv:{button:"Sūtīt atsauksmi",title:"Sūtīt atsauksmi",intro:"Atradi kļūdu, ir ideja vai jautājums? Apraksti to šeit.",note:"Ziņojums tiks atvērts kā jauns GitHub Issue. Vietnes autora e-pasts netiek publicēts.",program:"Programma",type:"Ziņojuma veids",message:"Ziņa",send:"Turpināt uz nosūtīšanu",bug:"Kļūda",suggestion:"Ieteikums",question:"Jautājums",other:"Cits",required:"Pirms nosūtīšanas ieraksti ziņu.",opening:"Atveru GitHub Issue…",pageLanguage:"Lapas valoda",source:"Avots"},
lt:{button:"Siųsti atsiliepimą",title:"Siųsti atsiliepimą",intro:"Radote klaidą, turite idėją ar klausimą? Aprašykite čia.",note:"Pranešimas bus atidarytas kaip naujas GitHub Issue. Svetainės autoriaus el. paštas neskelbiamas.",program:"Programa",type:"Pranešimo tipas",message:"Žinutė",send:"Tęsti siuntimą",bug:"Klaida",suggestion:"Pasiūlymas",question:"Klausimas",other:"Kita",required:"Prieš siųsdami parašykite žinutę.",opening:"Atidaromas GitHub Issue…",pageLanguage:"Puslapio kalba",source:"Šaltinis"},
lb:{button:"Feedback schécken",title:"Feedback schécken",intro:"E Feeler fonnt, eng Iddi oder eng Fro? Beschreif et hei.",note:"D'Meldung gëtt als neit GitHub Issue opgemaach. D'E-Mail-Adress vum Auteur gëtt net verëffentlecht.",program:"Programm",type:"Aart vun der Meldung",message:"Noriicht",send:"Weider fir ze schécken",bug:"Feeler",suggestion:"Virschlag",question:"Fro",other:"Aneres",required:"Schreif eng Noriicht ier s de schécks.",opening:"GitHub Issue gëtt opgemaach…",pageLanguage:"Sprooch vun der Säit",source:"Quell"},
mk:{button:"Испрати повратна информација",title:"Испрати повратна информација",intro:"Најдовте грешка, имате идеја или прашање? Опишете го тука.",note:"Пријавата ќе се отвори како нов GitHub Issue. Е-поштата на авторот на страницата не се објавува.",program:"Програма",type:"Тип на пријава",message:"Порака",send:"Продолжи кон испраќање",bug:"Грешка",suggestion:"Предлог",question:"Прашање",other:"Друго",required:"Напишете порака пред испраќање.",opening:"Се отвора GitHub Issue…",pageLanguage:"Јазик на страницата",source:"Извор"},
mt:{button:"Ibgħat feedback",title:"Ibgħat feedback",intro:"Sibt żball, għandek idea jew mistoqsija? Iddeskriviha hawn.",note:"Ir-rapport jinfetaħ bħala GitHub Issue ġdida. L-email tal-awtur tas-sit ma tiġix ippubblikata.",program:"Programm",type:"Tip ta' rapport",message:"Messaġġ",send:"Kompli biex tibgħat",bug:"Żball",suggestion:"Suġġeriment",question:"Mistoqsija",other:"Ieħor",required:"Ikteb messaġġ qabel tibgħat.",opening:"Qed jinfetaħ GitHub Issue…",pageLanguage:"Lingwa tal-paġna",source:"Sors"},
cnr:{button:"Pošalji povratnu informaciju",title:"Pošalji povratnu informaciju",intro:"Pronašli ste grešku, imate ideju ili pitanje? Opišite ovdje.",note:"Prijava će se otvoriti kao novi GitHub Issue. E-mail autora stranice nije objavljen.",program:"Program",type:"Vrsta prijave",message:"Poruka",send:"Nastavi na slanje",bug:"Greška",suggestion:"Prijedlog",question:"Pitanje",other:"Ostalo",required:"Unesite poruku prije slanja.",opening:"Otvaram GitHub Issue…",pageLanguage:"Jezik stranice",source:"Izvor"},
mo:{button:"Trimite feedback",title:"Trimite feedback",intro:"Ai găsit o eroare, ai o idee sau o întrebare? Descrie aici.",note:"Raportul se va deschide ca un nou GitHub Issue. Adresa de e-mail a autorului site-ului nu este publicată.",program:"Aplicație",type:"Tip de raport",message:"Mesaj",send:"Continuă spre trimitere",bug:"Eroare",suggestion:"Sugestie",question:"Întrebare",other:"Altul",required:"Scrie un mesaj înainte de trimitere.",opening:"Se deschide GitHub Issue…",pageLanguage:"Limba paginii",source:"Sursă"},
no:{button:"Send tilbakemelding",title:"Send tilbakemelding",intro:"Fant du en feil, har du en idé eller et spørsmål? Beskriv det her.",note:"Rapporten åpnes som en ny GitHub Issue. E-postadressen til nettstedets forfatter publiseres ikke.",program:"Program",type:"Type tilbakemelding",message:"Melding",send:"Fortsett til innsending",bug:"Feil",suggestion:"Forslag",question:"Spørsmål",other:"Annet",required:"Skriv en melding før du sender.",opening:"Åpner GitHub Issue…",pageLanguage:"Sidespråk",source:"Kilde"},
pt:{button:"Enviar feedback",title:"Enviar feedback",intro:"Encontrou um erro, tem uma ideia ou pergunta? Descreva aqui.",note:"O relatório será aberto como uma nova GitHub Issue. O e-mail do autor do site não é publicado.",program:"Aplicação",type:"Tipo de relatório",message:"Mensagem",send:"Continuar para enviar",bug:"Erro",suggestion:"Sugestão",question:"Pergunta",other:"Outro",required:"Escreva uma mensagem antes de enviar.",opening:"A abrir GitHub Issue…",pageLanguage:"Idioma da página",source:"Fonte"},
ro:{button:"Trimite feedback",title:"Trimite feedback",intro:"Ai găsit o eroare, ai o idee sau o întrebare? Descrie aici.",note:"Raportul se va deschide ca un nou GitHub Issue. Adresa de e-mail a autorului site-ului nu este publicată.",program:"Aplicație",type:"Tip de raport",message:"Mesaj",send:"Continuă spre trimitere",bug:"Eroare",suggestion:"Sugestie",question:"Întrebare",other:"Altul",required:"Scrie un mesaj înainte de trimitere.",opening:"Se deschide GitHub Issue…",pageLanguage:"Limba paginii",source:"Sursă"},
sr:{button:"Пошаљи повратну информацију",title:"Пошаљи повратну информацију",intro:"Пронашли сте грешку, имате идеју или питање? Опишите овде.",note:"Пријава ће се отворити као нови GitHub Issue. Имејл аутора сајта се не објављује.",program:"Програм",type:"Врста пријаве",message:"Порука",send:"Настави на слање",bug:"Грешка",suggestion:"Предлог",question:"Питање",other:"Остало",required:"Унесите поруку пре слања.",opening:"Отварам GitHub Issue…",pageLanguage:"Језик странице",source:"Извор"},
sk:{button:"Odoslať spätnú väzbu",title:"Odoslať spätnú väzbu",intro:"Našli ste chybu, máte nápad alebo otázku? Napíšte ju sem.",note:"Hlásenie sa otvorí ako nový GitHub Issue. E-mail autora stránky sa nezverejňuje.",program:"Aplikácia",type:"Typ hlásenia",message:"Správa",send:"Pokračovať k odoslaniu",bug:"Chyba",suggestion:"Návrh",question:"Otázka",other:"Iné",required:"Pred odoslaním napíšte správu.",opening:"Otváram GitHub Issue…",pageLanguage:"Jazyk stránky",source:"Zdroj"},
sl:{button:"Pošlji povratne informacije",title:"Pošlji povratne informacije",intro:"Ste našli napako, imate idejo ali vprašanje? Opišite tukaj.",note:"Prijava se bo odprla kot nov GitHub Issue. E-poštni naslov avtorja strani ni objavljen.",program:"Program",type:"Vrsta prijave",message:"Sporočilo",send:"Nadaljuj na pošiljanje",bug:"Napaka",suggestion:"Predlog",question:"Vprašanje",other:"Drugo",required:"Pred pošiljanjem napišite sporočilo.",opening:"Odpiram GitHub Issue…",pageLanguage:"Jezik strani",source:"Vir"},
es:{button:"Enviar comentarios",title:"Enviar comentarios",intro:"¿Encontraste un error, tienes una idea o una pregunta? Descríbelo aquí.",note:"El informe se abrirá como una nueva GitHub Issue. El correo del autor del sitio no se publica.",program:"Aplicación",type:"Tipo de informe",message:"Mensaje",send:"Continuar para enviar",bug:"Error",suggestion:"Sugerencia",question:"Pregunta",other:"Otro",required:"Escribe un mensaje antes de enviar.",opening:"Abriendo GitHub Issue…",pageLanguage:"Idioma de la página",source:"Origen"},
sw:{button:"Tuma maoni",title:"Tuma maoni",intro:"Umepata hitilafu, una wazo au swali? Eleza hapa.",note:"Ripoti itafunguliwa kama GitHub Issue mpya. Anwani ya barua pepe ya mwandishi wa tovuti haichapishwi.",program:"Programu",type:"Aina ya taarifa",message:"Ujumbe",send:"Endelea kutuma",bug:"Hitilafu",suggestion:"Pendekezo",question:"Swali",other:"Nyingine",required:"Andika ujumbe kabla ya kutuma.",opening:"Inafungua GitHub Issue…",pageLanguage:"Lugha ya ukurasa",source:"Chanzo"},
sv:{button:"Skicka feedback",title:"Skicka feedback",intro:"Hittade du ett fel, har du en idé eller en fråga? Beskriv det här.",note:"Rapporten öppnas som en ny GitHub Issue. Webbplatsens författares e-postadress publiceras inte.",program:"Program",type:"Typ av feedback",message:"Meddelande",send:"Fortsätt till skickande",bug:"Fel",suggestion:"Förslag",question:"Fråga",other:"Annat",required:"Skriv ett meddelande innan du skickar.",opening:"Öppnar GitHub Issue…",pageLanguage:"Sidans språk",source:"Källa"},
tr:{button:"Geri bildirim gönder",title:"Geri bildirim gönder",intro:"Bir hata mı buldunuz, fikriniz veya sorunuz mu var? Buraya yazın.",note:"Bildirim yeni bir GitHub Issue olarak açılır. Site yazarının e-posta adresi yayımlanmaz.",program:"Uygulama",type:"Bildirim türü",message:"Mesaj",send:"Göndermeye devam et",bug:"Hata",suggestion:"Öneri",question:"Soru",other:"Diğer",required:"Göndermeden önce bir mesaj yazın.",opening:"GitHub Issue açılıyor…",pageLanguage:"Sayfa dili",source:"Kaynak"},
uk:{button:"Надіслати відгук",title:"Надіслати відгук",intro:"Знайшли помилку, маєте ідею чи запитання? Опишіть тут.",note:"Звернення відкриється як новий GitHub Issue. Електронна адреса автора сайту не публікується.",program:"Програма",type:"Тип звернення",message:"Повідомлення",send:"Перейти до надсилання",bug:"Помилка",suggestion:"Пропозиція",question:"Запитання",other:"Інше",required:"Введіть повідомлення перед надсиланням.",opening:"Відкриваю GitHub Issue…",pageLanguage:"Мова сторінки",source:"Джерело"},
hi:{button:"फ़ीडबैक भेजें",title:"फ़ीडबैक भेजें",intro:"कोई त्रुटि मिली, सुझाव या प्रश्न है? यहाँ लिखें।",note:"रिपोर्ट एक नए GitHub Issue के रूप में खुलेगी। साइट लेखक का ईमेल पता प्रकाशित नहीं होता।",program:"ऐप",type:"रिपोर्ट प्रकार",message:"संदेश",send:"भेजने के लिए आगे बढ़ें",bug:"त्रुटि",suggestion:"सुझाव",question:"प्रश्न",other:"अन्य",required:"भेजने से पहले संदेश लिखें।",opening:"GitHub Issue खोला जा रहा है…",pageLanguage:"पृष्ठ की भाषा",source:"स्रोत"},
tg:{button:"Фиристодани фикр",title:"Фиристодани фикр",intro:"Хато ёфтед, пешниҳод ё савол доред? Дар ин ҷо нависед.",note:"Гузориш ҳамчун GitHub Issue-и нав кушода мешавад. Почтаи электронии муаллифи сомона нашр намешавад.",program:"Барнома",type:"Навъи гузориш",message:"Паём",send:"Идома ба фиристодан",bug:"Хато",suggestion:"Пешниҳод",question:"Савол",other:"Дигар",required:"Пеш аз фиристодан паём нависед.",opening:"GitHub Issue кушода мешавад…",pageLanguage:"Забони саҳифа",source:"Манбаъ"},
uz:{button:"Fikr yuborish",title:"Fikr yuborish",intro:"Xato topdingizmi, taklif yoki savolingiz bormi? Shu yerda yozing.",note:"Xabar yangi GitHub Issue sifatida ochiladi. Sayt muallifining e-pochta manzili e'lon qilinmaydi.",program:"Dastur",type:"Xabar turi",message:"Xabar",send:"Yuborishga o'tish",bug:"Xato",suggestion:"Taklif",question:"Savol",other:"Boshqa",required:"Yuborishdan oldin xabar yozing.",opening:"GitHub Issue ochilmoqda…",pageLanguage:"Sahifa tili",source:"Manba"},
isv:{button:"Poslati odzyv",title:"Poslati odzyv",intro:"Našli jeste grešku, imate ideju ili pytanje? Opišite tuto.",note:"Prijava se otvori kako novy GitHub Issue. E-mail autora stranice ne bude publikovany.",program:"Program",type:"Tip prijavy",message:"Poruka",send:"Prodolžiti k poslanju",bug:"Greška",suggestion:"Predlog",question:"Pytanje",other:"Ino",required:"Napišite poruku prěd poslanjem.",opening:"Otvarkuje se GitHub Issue…",pageLanguage:"Jezik stranice",source:"Izvor"}
};

feedbackTranslation = function(code = currentLanguageCode) {
    return window.AYO_FEEDBACK_UI[code] || window.AYO_FEEDBACK_UI.en;
};

submitFeedback = function(event) {
    event.preventDefault();
    const ui = feedbackTranslation();
    const honeypot = document.getElementById("feedback-website");
    const program = document.getElementById("feedback-program").value;
    const typeSelect = document.getElementById("feedback-type");
    const typeLabel = typeSelect.options[typeSelect.selectedIndex].textContent;
    const message = document.getElementById("feedback-message").value.trim();
    const status = document.getElementById("feedback-status");

    if (honeypot.value) { closeFeedback(); return; }
    if (!message) {
        status.textContent = ui.required;
        document.getElementById("feedback-message").focus();
        return;
    }

    const title = `[${program}] ${typeLabel}`;
    const body = [
        `## ${ui.program}`, program, "",
        `## ${ui.type}`, typeLabel, "",
        `## ${ui.message}`, message, "",
        "---",
        `${ui.pageLanguage}: ${LANGUAGES.find(item => item.code === currentLanguageCode)?.name || currentLanguageCode}`,
        `${ui.source}: ${window.location.href}`
    ].join("\n");

    const url = `${FEEDBACK_ISSUE_URL}?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;
    status.textContent = ui.opening;
    window.open(url, "_blank", "noopener,noreferrer");
    closeFeedback();
};
